/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_deficuet_unitykt_extension_TextureDecoder */

#ifndef _Included_io_github_deficuet_unitykt_extension_TextureDecoder
#define _Included_io_github_deficuet_unitykt_extension_TextureDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_deficuet_unitykt_extension_TextureDecoder
 * Method:    decodeDXT1
 * Signature: ([BII[B)I
 */
JNIEXPORT jint JNICALL Java_io_github_deficuet_unitykt_extension_TextureDecoder_decodeDXT1
  (JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray);

/*
 * Class:     io_github_deficuet_unitykt_extension_TextureDecoder
 * Method:    decodeDXT5
 * Signature: ([BII[B)I
 */
JNIEXPORT jint JNICALL Java_io_github_deficuet_unitykt_extension_TextureDecoder_decodeDXT5
  (JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray);

/*
 * Class:     io_github_deficuet_unitykt_extension_TextureDecoder
 * Method:    decodeBC4
 * Signature: ([BII[B)I
 */
JNIEXPORT jint JNICALL Java_io_github_deficuet_unitykt_extension_TextureDecoder_decodeBC4
  (JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray);

/*
 * Class:     io_github_deficuet_unitykt_extension_TextureDecoder
 * Method:    decodeBC5
 * Signature: ([BII[B)I
 */
JNIEXPORT jint JNICALL Java_io_github_deficuet_unitykt_extension_TextureDecoder_decodeBC5
  (JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray);

/*
 * Class:     io_github_deficuet_unitykt_extension_TextureDecoder
 * Method:    decodeBC6
 * Signature: ([BII[B)I
 */
JNIEXPORT jint JNICALL Java_io_github_deficuet_unitykt_extension_TextureDecoder_decodeBC6
  (JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray);

/*
 * Class:     io_github_deficuet_unitykt_extension_TextureDecoder
 * Method:    decodeBC7
 * Signature: ([BII[B)I
 */
JNIEXPORT jint JNICALL Java_io_github_deficuet_unitykt_extension_TextureDecoder_decodeBC7
  (JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray);

/*
 * Class:     io_github_deficuet_unitykt_extension_TextureDecoder
 * Method:    decodePVRTC
 * Signature: ([BII[BZ)I
 */
JNIEXPORT jint JNICALL Java_io_github_deficuet_unitykt_extension_TextureDecoder_decodePVRTC
  (JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray, jboolean);

/*
 * Class:     io_github_deficuet_unitykt_extension_TextureDecoder
 * Method:    decodeETC1
 * Signature: ([BII[B)I
 */
JNIEXPORT jint JNICALL Java_io_github_deficuet_unitykt_extension_TextureDecoder_decodeETC1
  (JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray);

/*
 * Class:     io_github_deficuet_unitykt_extension_TextureDecoder
 * Method:    decodeETC2
 * Signature: ([BII[B)I
 */
JNIEXPORT jint JNICALL Java_io_github_deficuet_unitykt_extension_TextureDecoder_decodeETC2
  (JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray);

/*
 * Class:     io_github_deficuet_unitykt_extension_TextureDecoder
 * Method:    decodeETC2A1
 * Signature: ([BII[B)I
 */
JNIEXPORT jint JNICALL Java_io_github_deficuet_unitykt_extension_TextureDecoder_decodeETC2A1
  (JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray);

/*
 * Class:     io_github_deficuet_unitykt_extension_TextureDecoder
 * Method:    decodeETC2A8
 * Signature: ([BII[B)I
 */
JNIEXPORT jint JNICALL Java_io_github_deficuet_unitykt_extension_TextureDecoder_decodeETC2A8
  (JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray);

/*
 * Class:     io_github_deficuet_unitykt_extension_TextureDecoder
 * Method:    decodeATCRGB4
 * Signature: ([BII[B)I
 */
JNIEXPORT jint JNICALL Java_io_github_deficuet_unitykt_extension_TextureDecoder_decodeATCRGB4
  (JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray);

/*
 * Class:     io_github_deficuet_unitykt_extension_TextureDecoder
 * Method:    decodeATCRGBA8
 * Signature: ([BII[B)I
 */
JNIEXPORT jint JNICALL Java_io_github_deficuet_unitykt_extension_TextureDecoder_decodeATCRGBA8
  (JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray);

/*
 * Class:     io_github_deficuet_unitykt_extension_TextureDecoder
 * Method:    decodeASTC
 * Signature: ([BII[BI)I
 */
JNIEXPORT jint JNICALL Java_io_github_deficuet_unitykt_extension_TextureDecoder_decodeASTC
  (JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray, jint);

/*
 * Class:     io_github_deficuet_unitykt_extension_TextureDecoder
 * Method:    decodeEACR
 * Signature: ([BII[B)I
 */
JNIEXPORT jint JNICALL Java_io_github_deficuet_unitykt_extension_TextureDecoder_decodeEACR
  (JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray);

/*
 * Class:     io_github_deficuet_unitykt_extension_TextureDecoder
 * Method:    decodeEACRSigned
 * Signature: ([BII[B)I
 */
JNIEXPORT jint JNICALL Java_io_github_deficuet_unitykt_extension_TextureDecoder_decodeEACRSigned
  (JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray);

/*
 * Class:     io_github_deficuet_unitykt_extension_TextureDecoder
 * Method:    decodeEACRG
 * Signature: ([BII[B)I
 */
JNIEXPORT jint JNICALL Java_io_github_deficuet_unitykt_extension_TextureDecoder_decodeEACRG
  (JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray);

/*
 * Class:     io_github_deficuet_unitykt_extension_TextureDecoder
 * Method:    decodeEACRGSigned
 * Signature: ([BII[B)I
 */
JNIEXPORT jint JNICALL Java_io_github_deficuet_unitykt_extension_TextureDecoder_decodeEACRGSigned
  (JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray);

/*
 * Class:     io_github_deficuet_unitykt_extension_TextureDecoder
 * Method:    decodeCrunchedDXT1
 * Signature: ([BII[BZ)I
 */
JNIEXPORT jint JNICALL Java_io_github_deficuet_unitykt_extension_TextureDecoder_decodeCrunchedDXT1
  (JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray, jboolean);

/*
 * Class:     io_github_deficuet_unitykt_extension_TextureDecoder
 * Method:    decodeCrunchedDXT5
 * Signature: ([BII[BZ)I
 */
JNIEXPORT jint JNICALL Java_io_github_deficuet_unitykt_extension_TextureDecoder_decodeCrunchedDXT5
  (JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray, jboolean);

/*
 * Class:     io_github_deficuet_unitykt_extension_TextureDecoder
 * Method:    decodeCrunchedETC1
 * Signature: ([BII[BZ)I
 */
JNIEXPORT jint JNICALL Java_io_github_deficuet_unitykt_extension_TextureDecoder_decodeCrunchedETC1
  (JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray, jboolean);

/*
 * Class:     io_github_deficuet_unitykt_extension_TextureDecoder
 * Method:    decodeCrunchedETC2A8
 * Signature: ([BII[BZ)I
 */
JNIEXPORT jint JNICALL Java_io_github_deficuet_unitykt_extension_TextureDecoder_decodeCrunchedETC2A8
  (JNIEnv *, jclass, jbyteArray, jint, jint, jbyteArray, jboolean);

#ifdef __cplusplus
}
#endif
#endif
